#line 2 "dealflex.c"

#line 4 "dealflex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 135
#define YY_END_OF_BUFFER 136
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[488] =
    {   0,
        0,    0,   22,   22,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  136,  134,  131,  132,
      134,    5,  134,  134,   17,  134,   15,   13,   14,  134,
       16,  124,  124,   19,    9,  134,   11,   18,  125,  125,
      120,  125,  125,  134,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  134,  134,   22,   24,
       23,  135,   54,   53,   55,   50,   49,   51,   62,   61,
      135,  135,  135,  135,   46,   45,  135,  135,  135,  135,
       58,   57,  135,   66,   65,  135,  135,  135,  135,  132,

        0,    8,    0,  128,  129,    3,  126,   21,    0,  127,
      124,    0,  121,   10,    7,   12,  125,  121,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,   76,   75,  130,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
       69,  125,    2,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,    1,    0,  133,   22,   23,   23,   25,   54,
       55,   50,   51,   62,    0,    0,    0,    0,   46,    0,

        0,   47,    0,   47,   58,    0,   59,   66,    0,    0,
        0,    0,  126,    0,   20,  127,  124,    0,   92,  125,
      125,    4,  112,  125,  102,  125,  125,  125,  125,  115,
      125,  125,  125,  125,  125,  125,  125,  125,   82,  125,
      109,  125,  125,  125,  114,  125,    6,  117,  125,  116,
      125,  125,  125,  125,   83,   85,   87,   89,   91,   93,
       95,   97,   99,  101,  125,  125,  113,  125,  125,  125,
      125,   84,  125,  125,  125,   70,  125,  125,  122,    0,
        0,    0,    0,   47,    0,    0,    0,    0,    0,    0,
      127,  123,  123,   92,  125,  125,  125,  107,   77,  125,

      125,  125,   42,  125,   72,  125,  125,  125,  125,  125,
       82,  125,  109,   86,   90,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,   84,
      125,   94,   96,   98,  100,  125,  119,  125,   74,  123,
      122,   63,    0,    0,   47,   47,   67,    0,    0,  124,
      125,  125,  125,   77,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,   79,   86,   90,  103,   71,  125,
      125,  125,  125,   31,  125,  125,   88,  108,  111,   73,
       80,  125,  104,  125,  122,   30,  125,  125,  125,  125,
       43,  125,  125,  125,  118,  125,  125,  125,   79,  103,

      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,   88,   80,   56,   56,  104,  125,  125,
       40,  125,  105,   60,   60,   78,  125,  125,  125,  110,
       81,   64,   64,  125,   26,  125,  125,   39,   34,   35,
      125,  125,  125,  125,  106,  125,   28,  125,  105,   78,
      125,  125,  125,   81,  125,   32,  125,  125,   33,  125,
       52,   52,  125,   29,  125,   41,   48,   48,  125,  125,
      125,   36,  125,  125,   27,  125,  125,  125,  125,  125,
      125,   44,   44,   68,   37,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,    1,    1,
        1,   11,   12,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,    1,   27,
       28,   29,   30,    1,   31,   32,   33,   33,   34,   35,
       36,   37,   36,   38,   39,   40,   36,   41,   42,   36,
       43,   36,   44,   45,   36,   36,   46,   36,   36,   36,
        1,   47,    1,    1,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,   69,   70,   71,   72,
       73,   74,    1,   75,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    4,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    2,    1,    2,    1,
        6,    6,    6,    7,    7,    6,    6,    6,    6,    6,
        6,    7,    6,    6,    6,    6,    1,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    5,    6,    6,    1
    } ;

static const flex_int16_t yy_base[499] =
    {   0,
        0,  884,   73,   76,  117,  141,  165,  189,  167,  169,
      192,  215,   75,   80,  177,  199,  890,  892,  892,  892,
       85,  861,   87,  105,  892,  878,  892,  892,  892,  129,
       80,   83,  160,  892,  859,  858,  857,  892,  218,    0,
      260,  838,  839,  820,   34,  241,   60,  126,  815,  827,
      218,  818,  829,  820,   38,   29,   50,  227,  807,  813,
      246,  162,  805,  820,  295,  304,  797,  868,    0,  892,
      162,  892,  868,  892,  312,  867,  892,  322,  866,  892,
      818,  803,  802,  811,  861,  892,  116,  136,  189,  306,
      860,  892,  197,  859,  892,  811,  796,  795,  804,  892,

      128,  892,  247,  892,  892,  892,  335,  892,  853,  358,
      202,  368,  892,  892,  892,  892,    0,    0,    0,  837,
      254,  268,  343,  376,  381,  380,  823,  377,  375,  378,
      391,    0,    0,  892,  359,  785,  223,  799,  832,  799,
      780,  786,  777,  779,  796,  795,  776,  793,  777,  787,
      777,  771,  773,  787,  771,  783,  771,  765,  780,  191,
        0,  315,    0,  764,  772,  375,  425,  382,  776,  764,
      777,  756,  775,  761,  754,  757,  763,  759,  751,  435,
      428,  429,  892,  814,  892,    0,  422,  452,  892,  814,
      458,  813,  468,  812,  746,  746,  742,  743,  807,  203,

      304,  892,  453,  892,  806,  404,  892,  805,  739,  739,
      735,  736,  892,  799,  892,  479,  500,  510,  734,  743,
      748,    0,    0,  732,    0,  746,  746,  169,  729,    0,
      734,  732,  724,  731,  727,  724,  735,  736,  719,  719,
      717,  724,  727,  728,    0,  712,  713,    0,  716,    0,
      715,  724,  713,  722,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  713,  719,    0,  705,  706,  701,
      716,  700,  706,  490,  485,  703,  696,  521,  691,  694,
      693,  692,  691,  892,  510,  514,  690,  689,  688,  687,
      892,  567,  892,    0,  691,  690,  703,    0,  684,  693,

      683,  684,  694,  683,    0,  694,  678,  674,  676,  692,
        0,  672,    0,  672,  671,  671,  680,  666,  681,  665,
      679,  663,  661,  672,  666,  674,  673,  669,  671,    0,
      670,    0,    0,    0,    0,  663,    0,  668,    0,    0,
      648,  892,  663,  662,  892,  892,  892,  661,  660,  578,
      653,  645,  658,    0,  644,  648,  642,  643,  646,  644,
      638,  652,  655,  637,  635,    0,    0,  634,    0,  639,
      633,  647,  648,  501,  645,  627,  627,    0,    0,    0,
      626,  304,  625,  625,    0,    0,  628,  636,  631,  627,
        0,  368,  634,  623,    0,  622,  615,  630,    0,    0,

      617,  503,  617,  619,  618,  614,  397,  609,  613,  624,
      616,  619,  598,    0,    0,  668,  892,    0,  620,  600,
        0,  604,  599,  663,  892,  577,  571,  587,  528,    0,
      513,  577,  892,  509,    0,  517,  515,    0,    0,    0,
      522,  512,  521,  510,    0,  521,    0,  508,    0,    0,
      503,  489,  553,    0,  499,    0,  496,  493,    0,  498,
      547,  892,  454,    0,  422,    0,  437,  892,  358,  375,
      356,    0,  312,  249,    0,  243,  227,  556,  159,   41,
       45,   78,  892,    0,    0,    0,  892,  603,  610,  617,
      621,  622,  629,  636,  642,  648,  655,  659

    } ;

static const flex_int16_t yy_def[499] =
    {   0,
      487,    1,  488,  488,  489,  489,  489,  489,  489,  489,
      489,  489,  489,  489,  489,  489,  487,  487,  487,  487,
      487,  487,  490,  487,  487,  487,  487,  487,  487,  487,
      487,  491,  491,  487,  487,  487,  487,  487,  492,  492,
      492,  492,  492,  487,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  487,  493,  494,  487,
      495,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  496,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  490,  487,  487,  487,  487,  487,  497,  487,
      498,  487,  487,  487,  487,  487,  492,  492,  492,  492,
      492,  492,  492,  492,  492,   41,   41,   41,   41,   41,
       41,  492,  492,  487,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      180,  492,  487,  493,  487,  494,  495,  495,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  496,  487,  487,  487,  487,
      487,  487,  487,  497,  487,  487,  487,  487,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  492,  492,  492,  492,  492,  492,  492,

      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,

      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  487,  487,  492,  492,  492,
      492,  492,  492,  487,  487,  492,  492,  492,  492,  492,
      492,  487,  487,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      487,  487,  492,  492,  492,  492,  487,  487,  492,  492,
      492,  492,  492,  492,  492,  492,  492,  492,  492,  492,
      492,  487,  487,  492,  492,  492,    0,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487

    } ;

static const flex_int16_t yy_nxt[968] =
    {   0,
       18,   19,   20,   21,   22,   23,   18,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   32,   33,   33,   33,
       33,   33,   33,   33,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   40,   40,   41,   39,   39,   40,
       43,   40,   39,   41,   39,   40,   44,   18,   45,   40,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       40,   56,   57,   58,   59,   60,   61,   62,   40,   63,
       64,   65,   40,   66,   67,   70,   91,   92,   70,  482,
       93,   91,   92,   71,  135,   93,   71,  100,  101,  104,
      108,  160,  104,  136,  109,  137,  110,  486,  161,   72,

      158,   72,   72,  138,   72,  159,   72,   72,  485,   72,
       72,  144,  145,  162,   72,  163,  146,   72,   73,   74,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      100,  101,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   73,   74,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  112,  200,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   76,   77,   79,   80,
       79,   80,  188,  110,  147,  200,  189,  201,   94,   95,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       76,   77,  113,   85,   86,  148,  113,  149,  201,  207,

       94,   95,  207,  113,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,  174,  110,   85,   86,  175,   81,
      300,   81,   87,   88,  176,   89,  484,  177,   82,   96,
       82,  112,   90,   83,  202,   83,  301,   84,   97,   84,
       87,   88,  284,   98,   89,   87,   88,   99,   89,  104,
      118,   96,  104,   90,  118,   90,  246,  139,  247,  202,
       97,  118,  284,   87,   88,   98,  152,   89,  153,   99,
      154,  119,  120,  218,  222,  164,   90,  119,  120,  121,
      122,  123,  124,  125,  126,  119,  120,  121,  481,  165,
      127,  140,  166,  480,  167,  223,  170,  128,  129,  479,

      141,  171,  130,  142,  131,  416,  417,  143,  172,  173,
      180,  181,  181,  181,  181,  181,  181,  181,  180,  180,
      182,  182,  182,  182,  182,  182,  182,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  203,  285,  204,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      119,  120,  121,  122,  478,  248,  180,  249,  203,  424,
      425,  285,  204,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  119,  120,  121,  122,  123,  119,  120,

      121,  122,  123,  124,  117,  117,  207,  117,  117,  207,
      117,  219,  477,  117,  117,  117,  117,  117,  117,  117,
      117,  117,  117,  476,  117,  475,  220,  252,  117,  117,
      265,  253,  487,  117,  266,  117,  487,  254,  467,  218,
      255,  256,  257,  258,  259,  260,  261,  262,  263,  264,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      279,  279,  188,  438,  279,  279,  189,  439,  279,  279,
      474,  279,  279,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  286,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  432,  433,  278,  332,  333,  334,
      335,  461,  462,  473,  286,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  336,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  345,  346,  461,  405,
      472,  406,  471,  407,  467,  468,  337,  482,  483,  470,
      469,  466,  408,  409,  410,  345,  346,  411,  465,  464,
      463,  293,  460,  459,  458,  457,  456,  455,  432,  454,
      453,  293,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  340,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,   69,   69,   69,   69,   69,   69,   69,
       72,   72,   72,   72,   72,   72,   72,  103,  103,  103,
      103,  103,  103,  103,  111,  111,  117,  117,  117,  184,
      184,  184,  184,  184,  184,  184,  186,  452,  451,  186,
      186,  186,  187,  450,  187,  187,  187,  187,  206,  206,
      206,  206,  206,  206,  206,  214,  214,  214,  214,  214,
      214,  214,  217,  217,  424,  449,  448,  447,  446,  416,
      445,  444,  443,  442,  441,  440,  437,  436,  435,  434,
      431,  430,  429,  428,  427,  426,  423,  422,  421,  420,
      419,  418,  415,  414,  413,  412,  404,  403,  402,  401,

      400,  399,  398,  397,  396,  395,  394,  393,  392,  391,
      390,  389,  388,  387,  386,  347,  347,  342,  342,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  347,  349,  348,  347,  342,  344,
      343,  342,  341,  339,  338,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  299,  298,  297,  296,  295,

      294,  215,  290,  289,  288,  287,  208,  205,  199,  283,
      282,  281,  280,  194,  192,  190,  185,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  251,  250,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  221,  117,  119,  215,  212,  211,  210,  209,
      208,  205,  199,  198,  197,  196,  195,  194,  192,  190,
      185,  183,  179,  178,  169,  168,  157,  156,  155,  151,
      150,  134,  133,  132,  116,  115,  114,  106,  102,  487,
       68,   17,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487
    } ;

static const flex_int16_t yy_chk[968] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,   13,   13,    4,  482,
       13,   14,   14,    3,   45,   14,    4,   21,   21,   23,
       31,   56,   23,   45,   31,   45,   32,  481,   56,    3,

       55,    3,    4,   45,    4,   55,    3,    3,  480,    4,
        4,   47,   47,   57,    3,   57,   47,    4,    5,    5,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
      101,  101,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    6,    6,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   87,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    7,    7,    9,    9,
       10,   10,   71,   33,   48,   87,   71,   88,   15,   15,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        8,    8,   33,   11,   11,   48,   33,   48,   88,   93,

       16,   16,   93,   33,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,   62,  111,   12,   12,   62,    9,
      228,   10,   11,   11,   62,   11,  479,   62,    9,   15,
       10,   33,   11,    9,   89,   10,  228,    9,   15,   10,
       11,   11,  200,   15,   11,   12,   12,   15,   12,  103,
       39,   16,  103,   11,   39,   12,  160,   46,  160,   89,
       16,   39,  200,   12,   12,   16,   51,   12,   51,   16,
       51,  121,  121,  111,  137,   58,   12,   41,   41,   41,
       41,   41,   41,   41,   41,  122,  122,  122,  477,   58,
       41,   46,   58,  476,   58,  137,   61,   41,   41,  474,

       46,   61,   41,   46,   41,  382,  382,   46,   61,   61,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       66,   66,   66,   66,   66,   66,   66,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   90,  201,   90,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      123,  123,  123,  123,  473,  162,   65,  162,   90,  392,
      392,  201,   90,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  110,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  124,  124,  124,  124,  124,  125,  125,

      125,  125,  125,  125,  126,  129,  206,  128,  130,  206,
      126,  135,  471,  129,  128,  128,  130,  126,  126,  128,
      130,  131,  126,  470,  126,  469,  135,  166,  131,  131,
      168,  166,  187,  131,  168,  131,  187,  166,  467,  112,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      181,  182,  188,  407,  181,  182,  188,  407,  181,  182,
      465,  181,  182,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  203,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  402,  402,  180,  274,  274,  274,
      274,  444,  444,  463,  203,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  275,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  285,  286,  461,  374,
      460,  374,  458,  374,  453,  453,  275,  478,  478,  457,
      455,  452,  374,  374,  374,  285,  286,  374,  451,  448,
      446,  217,  443,  442,  441,  437,  436,  434,  432,  431,
      429,  218,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  278,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  488,  488,  488,  488,  488,  488,  488,
      489,  489,  489,  489,  489,  489,  489,  490,  490,  490,
      490,  490,  490,  490,  491,  491,  492,  492,  492,  493,
      493,  493,  493,  493,  493,  493,  494,  428,  427,  494,
      494,  494,  495,  426,  495,  495,  495,  495,  496,  496,
      496,  496,  496,  496,  496,  497,  497,  497,  497,  497,
      497,  497,  498,  498,  424,  423,  422,  420,  419,  416,
      413,  412,  411,  410,  409,  408,  406,  405,  404,  403,
      401,  398,  397,  396,  394,  393,  390,  389,  388,  387,
      384,  383,  381,  377,  376,  375,  373,  372,  371,  370,

      368,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  353,  352,  351,  349,  348,  344,  343,  341,
      338,  336,  331,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  312,
      310,  309,  308,  307,  306,  304,  303,  302,  301,  300,
      299,  297,  296,  295,  290,  289,  288,  287,  283,  282,
      281,  280,  279,  277,  276,  273,  272,  271,  270,  269,
      268,  266,  265,  254,  253,  252,  251,  249,  247,  246,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  229,  227,  226,  224,  221,  220,

      219,  214,  212,  211,  210,  209,  208,  205,  199,  198,
      197,  196,  195,  194,  192,  190,  184,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  165,  164,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  136,  127,  120,  109,   99,   98,   97,   96,
       94,   91,   85,   84,   83,   82,   81,   79,   76,   73,
       68,   67,   64,   63,   60,   59,   54,   53,   52,   50,
       49,   44,   43,   42,   37,   36,   35,   26,   22,   17,
        2,  487,  487,  487,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  487,  487,  487
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[136] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 
    1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../src/dealflex.l"
/* Pre --  Stuff here ignored by FLEX */
/* JGM 2021-11-17   Defined the USER ACTION macro in flex so that flex can update the yylloc with yylineno for bison */
/* JGM 2021-11-17   Eliminated the need for lino; using %option yylineno instead. Also other Mods */
/* JGM 2021-11-10   %x states so produce,generate,title,opener,dealer,vulnerable, now handled in flex not yacc */
/* JGM 2021-11-04   Added a pattern for DECNUM -- returns 100 * the value so 99.99 becomes an int 9999 */
/* JGM 2022-02-03   Changed the pattern for vulnerable to be case insensitive (?i: ... ) */
/* JGM 2022-02-04   Fixed Exclusion states to handle whitespace and newlines. Prob should handle 'other' chars also. TBD */
/* JGM 2022-02-04   Adding in the YY_STATE_BUFF and yy_parse_string stuff, for script var text substitution  Scriptvar*/
/* JGM 2022-02-07   Adding the csvlist and CSVRPT mods */
/* JGM 2022-02-12   Adding the trix function token processing. */
#line 12 "../src/dealflex.l"
 #ifndef _GNU_SOURCE
   #define _GNU_SOURCE
 #endif
  /* Prolog: This code copied to the output file created by Flex */
  /* Need some include statements here for e.g. y.tab.h etc. */
 float flexvers = 4.0 ; /* for debugging and version tracking */
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
 #include "../include/dealdefs.h"
 #include "../include/dealtypes.h"
 #include "../include/dealexterns.h"  /* for maxgenerate, maxproduce, maxdealer, and maxvuln, title etc. */
 #include "../include/dealprotos.h"  /* for my_strcpy, ... */
 #include "dealyacc.tab.h"          /* for all the token definitions */

 #define YY_USER_ACTION yylloc.first_line = yylloc.last_line = yylineno;

   /* Following added for script variable ($0 - $9 ) processing */
  YY_BUFFER_STATE yy_script_buff ;  /* opaque struct var to get input from a string */
  YY_BUFFER_STATE yy_cur_buff;      /* opaque struct var to save Input File buffer  */
  int in_str_buff = 0 ;             /* Flag to us that EOF condition was on string buff, not Input File buff */
  int scr_vnum;                     /* Subscript into the script_parm array */

  #define BUFFLEN 255
  char buff[BUFFLEN + 1] = {'\0'};                  /* to copy yytext for local processing */
  char *c_ptr;
  long int dotpos ;
  int dotnumval ;

  /* modified yywrap to handle EOF on a script string buffer as well as the original input file buffer */
  /* Calling yywrap is the default <<EOF>> rule */

  int yywrap () {
   if (!in_str_buff ) {  /* End of Input File, means yyparse() is done */

      #ifdef JGMDBG
        if(jgmDebug >=3) { fprintf(stderr, "FLEX::Processed %d lines in Input File. Exit to main now. \n", yylineno ); }
       #endif

       return 1 ;      /* yylex is alldone. No more input */
   } /* end if Not in_str_buff */

   /* EOF was not on Input File, but rather on a script variable string buffer */
   /* Reclaim RAM, pop state, and continue with Input File */
   yy_delete_buffer( yy_script_buff );
   yypop_buffer_state();
   in_str_buff--;
   yy_switch_to_buffer(yy_cur_buff);
      #ifdef JGMDBG
        if(jgmDebug >=3) {fprintf( stderr, "Script var ended. Back to reading Input File.  in_str_buff=[%d]\n", in_str_buff );}
      #endif
   return 0 ; /* not all done yet. */
} /* end yywrap */

  /* routines to set global vars for PBN printing for dealer and Vulnerable */
 int compass2int( char *s ) {    /* checking for north , east , south , west */
  #ifdef JGMDBG
     if(jgmDebug >= 3) { fprintf(stderr, "FLEX::In compass2int with string [%s]\n", s) ; }
  #endif
    if      (strchr(s, 'n' ) || strchr(s, 'N') ) { return COMPASS_NORTH ; }
    else if (strchr(s, 'a' ) || strchr(s, 'A') ) { return COMPASS_EAST  ; }
    else if (strchr(s, 'u' ) || strchr(s, 'U') ) { return COMPASS_SOUTH ; }
    else if (strchr(s, 'w' ) || strchr(s, 'W') ) { return COMPASS_WEST  ; }
    return 0 ;  /* default to north */
 } /* end compass2int */

 int vul2int(char *s ) {         /* checking for none, NS, EW , all, both */
    #ifdef JGMDBG
       if(jgmDebug >= 3) { fprintf(stderr,"FLEX::In vul2int with side=[%s] at yylineno[%d]\n", s, yylineno) ; }
    #endif
    if      (strchr(s, 'o' ) || strchr(s, 'O') ) { return VULNERABLE_NONE ; }
    else if (strchr(s, 's' ) || strchr(s, 'S') ) { return VULNERABLE_NS   ; }
    else if (strchr(s, 'w' ) || strchr(s, 'W') ) { return VULNERABLE_EW   ; }
    else if (strchr(s, 'a' ) || strchr(s, 'A') ) { return VULNERABLE_ALL  ; }
    else if (strchr(s, 'b' ) || strchr(s, 'B') ) { return VULNERABLE_NS   ; }
    return 0 ; /* default to none */
} /* end vul2int*/

#line 938 "dealflex.c"
#line 92 "../src/dealflex.l"
        /* Flex Declarations section: States, aliases etc. */
    /* Ask Flex to keep track of the input line number -- the user action macro (line 15) will also pass yylineno to bison*/
 /* Define Exclusive states to handle text processed within Flex */







        /* These aliases are to make the patterns in Flex easier to write and to read */
        /* You cant put comments on lines that define aliases */
    /* Note that shape will override digits, even in the case of 4432 5332 etc since it comes BEFORE digits in the rules */
   /* JGM added underscore to above definition of an id */
  /*  This next one should be useful to get numbers of the form nn.mm for LTC, CCCC, Suit Quality OPC etc. */
  /* Handles for example:  .5 , .25 , 0.1 , 0.77, 12. , 12.0, 12.05, 12.76 , 2., 2.0, 2.1 , 2.05 , 2.95, etc. */
  /* Since there are no other words in dealer that use a DOT any time we see digits next to a dot it is a dotnum aka DECNUM */
  /* Note that dotnum will override digits when appropriate since n. and nn. are both longer than n or nn */
 /* Enter Matching Rules section  {bol}pattern   { C code to execute when pattern matches }  */
#line 959 "dealflex.c"

#define INITIAL 0
#define COMMENT 1
#define MAXPROD 2
#define MAXGEN 3
#define MAXDEAL 4
#define MAXVUL 5
#define TITLE 6
#define OPENER 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 126 "../src/dealflex.l"

#line 1188 "dealflex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 488 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 892 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 127 "../src/dealflex.l"
return(OR2);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 128 "../src/dealflex.l"
return(OR2);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 129 "../src/dealflex.l"
return(AND2);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 130 "../src/dealflex.l"
return(AND2);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 131 "../src/dealflex.l"
return(NOT);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 132 "../src/dealflex.l"
return(NOT);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 133 "../src/dealflex.l"
return(CMPEQ);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 134 "../src/dealflex.l"
return(CMPNE);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 135 "../src/dealflex.l"
return(CMPLT);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 136 "../src/dealflex.l"
return(CMPLE);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 137 "../src/dealflex.l"
return(CMPGT);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 138 "../src/dealflex.l"
return(CMPGE);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 139 "../src/dealflex.l"
return(ARPLUS);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 140 "../src/dealflex.l"
return(ARMINUS);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 141 "../src/dealflex.l"
return(ARTIMES);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 142 "../src/dealflex.l"
return(ARDIVIDE);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 143 "../src/dealflex.l"
return(ARMOD);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 144 "../src/dealflex.l"
return(QUERY);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 145 "../src/dealflex.l"
return(COLON);
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 146 "../src/dealflex.l"
;                       /* do nothing if C style one line comment */
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 147 "../src/dealflex.l"
BEGIN(COMMENT);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 148 "../src/dealflex.l"
/*In Comment State:  eat up non-star, non EOL and non EOF .. */
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 149 "../src/dealflex.l"
/*                   eat one or more * if followed by non *, non / non EOL non EOF */
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 150 "../src/dealflex.l"
;                       /* do nothing if {nl} found. flex will track yylineno */
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 151 "../src/dealflex.l"
yyerror("EOF found in comment");       /*yyerror prints and then does exit(-1) */
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 152 "../src/dealflex.l"
BEGIN(INITIAL);                        /* found one or more * with a slash next to. Exit state COMMENT */
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 154 "../src/dealflex.l"
return(PREDEAL);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 155 "../src/dealflex.l"
return(POINTCOUNT);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 156 "../src/dealflex.l"
return(ALTCOUNT);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 157 "../src/dealflex.l"
return(CONDITION);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 158 "../src/dealflex.l"
return(ACTION);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 159 "../src/dealflex.l"
return(PRINT);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 160 "../src/dealflex.l"
return(PRINTALL);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 161 "../src/dealflex.l"
return(PRINTPBN);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 162 "../src/dealflex.l"
return(PRINTEW);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 163 "../src/dealflex.l"
return(PRINTNS);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 164 "../src/dealflex.l"
return(PRINTSIDE);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 165 "../src/dealflex.l"
return(PRINTCOMPACT);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 166 "../src/dealflex.l"
return(PRINTONELINE);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 167 "../src/dealflex.l"
return(PRINTES);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 168 "../src/dealflex.l"
return(AVERAGE);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 169 "../src/dealflex.l"
return(FREQUENCY);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 170 "../src/dealflex.l"
return(DEAL);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 171 "../src/dealflex.l"
return(CSVRPT);
	YY_BREAK
/* now do some direct handling of the cases where yyparse not needed. It simplifies the yyparse() and the grammar */
/* We do have to allow for the fact that the user might enter the keyword
    * e.g. generate on a different line from the value e.g. 1000000
    * Rather than define a pattern that can span multiple lines we use the exclusive states feature of Flex
    */
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 178 "../src/dealflex.l"
{ BEGIN(MAXVUL);   }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 179 "../src/dealflex.l"
;                 /* do nothing if {nl} found. flex will track yylineno */
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 180 "../src/dealflex.l"
;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 181 "../src/dealflex.l"
{ strncpy(buff, yytext, yyleng) ; buff[yyleng]='\0';
                                    maxvuln = vul2int(buff) ; yylval.y_int = maxvuln ;
                                    BEGIN(INITIAL) ;
                                 }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 186 "../src/dealflex.l"
{ BEGIN(MAXGEN);  }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 187 "../src/dealflex.l"
;                /* do nothing if {nl} found. flex will track yylineno */
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 188 "../src/dealflex.l"
;                  /* just eat up ws */
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 189 "../src/dealflex.l"
{ strncpy(buff, yytext, yyleng) ; buff[yyleng]='\0';
                            if (!maxgenerate) maxgenerate = atoi(buff)   ;
                            yylval.y_int = maxgenerate ;
                            BEGIN(INITIAL) ;
                  }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 195 "../src/dealflex.l"
{ BEGIN(MAXPROD);   }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 196 "../src/dealflex.l"
;                /* do nothing if {nl} found. flex will track yylineno */
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 197 "../src/dealflex.l"
;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 198 "../src/dealflex.l"
{ strncpy(buff, yytext, yyleng) ; buff[yyleng]='\0';
                        if (!maxproduce ) maxproduce  = atoi(buff)   ;
                        yylval.y_int = maxproduce ;
                        BEGIN(INITIAL) ;
                  }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 203 "../src/dealflex.l"
{ BEGIN(TITLE);  }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 204 "../src/dealflex.l"
;                /* do nothing if {nl} found. flex will track yylineno */
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 205 "../src/dealflex.l"
;
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 206 "../src/dealflex.l"
{
                    strncpy(title, yytext+1, (yyleng-2) ) ;
                    title[yyleng-2] = '\0';
                    title_len = strlen(title) ;
                    BEGIN(INITIAL) ;
                  }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 213 "../src/dealflex.l"
{ BEGIN(MAXDEAL); }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 214 "../src/dealflex.l"
;                /* do nothing if {nl} found. flex will track yylineno */
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 215 "../src/dealflex.l"
;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 216 "../src/dealflex.l"
{ strncpy(buff, yytext, yyleng) ; buff[yyleng] = '\0';
                                     maxdealer = compass2int(buff); yylval.y_int = maxdealer ;
                                     BEGIN(INITIAL) ;
                                    }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 221 "../src/dealflex.l"
{ BEGIN(OPENER); }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 222 "../src/dealflex.l"
;                /* do nothing if {nl} found. flex will track yylineno */
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 223 "../src/dealflex.l"
;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 224 "../src/dealflex.l"
{ strncpy(buff, yytext, yyleng) ; buff[yyleng] = '\0';
                                     Opener = compass2int(buff); yylval.y_int = Opener ;
                                     BEGIN(INITIAL) ;
                                    }
	YY_BREAK
/* evalcontract is an action that prints the average score for the given contract */
/* User can specify any contract from 1C to 7N re-doubled,  nv and vul, for either side  */
case 68:
YY_RULE_SETUP
#line 230 "../src/dealflex.l"
{ return(EVALCONTRACT); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 231 "../src/dealflex.l"
{ yylval.y_int = NON_VUL; return VULN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 232 "../src/dealflex.l"
{ yylval.y_int = VUL; return VULN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 234 "../src/dealflex.l"
{ yylval.y_int = COMPASS_NORTH; return COMPASS; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 235 "../src/dealflex.l"
{ yylval.y_int = COMPASS_EAST; return COMPASS; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 236 "../src/dealflex.l"
{ yylval.y_int = COMPASS_SOUTH; return COMPASS; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 237 "../src/dealflex.l"
{ yylval.y_int = COMPASS_WEST; return COMPASS; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 238 "../src/dealflex.l"
{ yylval.y_int = SIDE_NS ; return SIDE ; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 239 "../src/dealflex.l"
{ yylval.y_int = SIDE_EW ; return SIDE ; }
	YY_BREAK
/* These next rules match both singular and plural form, ie. club and clubs or hcp and hcps the 's' is optional */
case 77:
YY_RULE_SETUP
#line 242 "../src/dealflex.l"
{ yylval.y_int = SUIT_CLUB; return SUIT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 243 "../src/dealflex.l"
{ yylval.y_int = SUIT_DIAMOND; return SUIT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 244 "../src/dealflex.l"
{ yylval.y_int = SUIT_HEART; return SUIT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 245 "../src/dealflex.l"
{ yylval.y_int = SUIT_SPADE; return SUIT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 247 "../src/dealflex.l"
return NOTRUMPS;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 248 "../src/dealflex.l"
return(HCP);            /* Note you can have variables hcpn, hcpe, hcpw but NOT hcps */
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 249 "../src/dealflex.l"
return(PT0);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 250 "../src/dealflex.l"
return(PT0);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 251 "../src/dealflex.l"
return(PT1);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 252 "../src/dealflex.l"
return(PT1);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 253 "../src/dealflex.l"
return(PT2);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 254 "../src/dealflex.l"
return(PT2);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 255 "../src/dealflex.l"
return(PT3);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 256 "../src/dealflex.l"
return(PT3);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 257 "../src/dealflex.l"
return(PT4);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 258 "../src/dealflex.l"
return(PT4);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 259 "../src/dealflex.l"
return(PT5);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 260 "../src/dealflex.l"
return(PT5);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 261 "../src/dealflex.l"
return(PT6);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 262 "../src/dealflex.l"
return(PT6);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 263 "../src/dealflex.l"
return(PT7);
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 264 "../src/dealflex.l"
return(PT7);
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 265 "../src/dealflex.l"
return(PT8);
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 266 "../src/dealflex.l"
return(PT8);
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 267 "../src/dealflex.l"
return(PT9);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 268 "../src/dealflex.l"
return(PT9);
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 269 "../src/dealflex.l"
return(LOSER);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 270 "../src/dealflex.l"
return(TRICKS);
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 271 "../src/dealflex.l"
return(CONTROL);
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 272 "../src/dealflex.l"
return(QUALITY);
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 273 "../src/dealflex.l"
return(CCCC);
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 274 "../src/dealflex.l"
return(SCORE);
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 275 "../src/dealflex.l"
return(IMPS);
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 276 "../src/dealflex.l"
return(HASCARD);
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 277 "../src/dealflex.l"
return(SHAPE);
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 278 "../src/dealflex.l"
return(ANY);
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 279 "../src/dealflex.l"
return(RND);
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 280 "../src/dealflex.l"
return(LTC);
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 281 "../src/dealflex.l"
return(DDS);
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 282 "../src/dealflex.l"
return(PAR);
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 283 "../src/dealflex.l"
return(OPC);
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 284 "../src/dealflex.l"
return(EXPORT);
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 285 "../src/dealflex.l"
return(TRIX);
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 288 "../src/dealflex.l"
{ yylval.y_str = mystrcpy(yytext); return HOLDING; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 289 "../src/dealflex.l"
{ yylval.y_int = make_card(yytext[0], yytext[1]);         return(CARD);   }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 291 "../src/dealflex.l"
{ yylval.y_int = make_contract(&yytext[1]) ; // encode the contract as a number (5..39) + (40*UND|DBL|RDBL)
                            return(CONTRACT);
                        }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 295 "../src/dealflex.l"
{ strncpy(yylval.y_distr, yytext, 8);
                  if (strchr(yytext, 'x') )  { return DISTR; }
                  else                       { return DISTR_OR_NUMBER; }
                }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 301 "../src/dealflex.l"
{ yylval.y_int = atoi(yytext); return NUMBER; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 302 "../src/dealflex.l"
{ yylval.y_str = mystrcpy(yytext); return IDENT; }
	YY_BREAK
case 126:
#line 305 "../src/dealflex.l"
case 127:
YY_RULE_SETUP
#line 305 "../src/dealflex.l"
{ yylval.y_decnum = (int)(100. * atof(yytext) ) ; /* will handle minus signs */
                  return DECNUM ;
                }
	YY_BREAK
case 128:
/* rule 128 can match eol */
YY_RULE_SETUP
#line 309 "../src/dealflex.l"
{ yylval.y_str = strdup(yytext+1); /* skip open quote */
                  if (yylval.y_str[yyleng-2] != '"') {
                    fprintf(stderr,"Unterminated character string\n");
                    return STRING ;
                  }
                  else {
                    yylval.y_str[yyleng-2] = '\0'; /* remove close quote */
                    /* printf("Found string at line[%d]\n", yylineno );   // shows that yylineno works */
                    return STRING;
                  }
                }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 320 "../src/dealflex.l"
{
               /* Save current input buffer context, open new buffer based on a string, and make it the current one */
             yy_cur_buff = YY_CURRENT_BUFFER;
             scr_vnum = *(yytext+1) - '0' ; /* cheap atoi conversion */
             yy_script_buff = yy_scan_string( parm.script_var[scr_vnum] ) ; /* a global var filled by the getopts() function */
             yypush_buffer_state(yy_script_buff) ;
             in_str_buff++ ;  /* maybe not req'd but don't know how to avoid it */
             #ifdef JGMDBG
               if(jgmDebug >= 3 ) {
                  fprintf(stderr, " A Dollar sign Script variable : %s\n", yytext ) ;
                  fprintf(stderr, "scan_string state pushed. in_str_buff = [%d], scr_vnum=[%d]\n", in_str_buff, scr_vnum);
                  fprintf(stderr, "script_var[%d]=%s\n", scr_vnum, parm.script_var[scr_vnum] ) ;
               }
             #endif
          }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 336 "../src/dealflex.l"
{ yylval.y_str = mystrcpy("\n"); return STRING; }  /* need this one for printes LF */
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 337 "../src/dealflex.l"
;
	YY_BREAK
case 132:
/* rule 132 can match eol */
YY_RULE_SETUP
#line 338 "../src/dealflex.l"
{ ; }                 /* do nothing if {nl} found. flex will track yylineno */
	YY_BREAK
case 133:
/* rule 133 can match eol */
YY_RULE_SETUP
#line 339 "../src/dealflex.l"
{ ; }                 /* # in col1 is a comment. Do nothing. flex will track yylineno */
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 340 "../src/dealflex.l"
return(yytext[0]);    /* unknown char; handles stuff like , ; may trigger error in yyparse if unexpected */
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 342 "../src/dealflex.l"
ECHO;
	YY_BREAK
#line 2011 "dealflex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MAXPROD):
case YY_STATE_EOF(MAXGEN):
case YY_STATE_EOF(MAXDEAL):
case YY_STATE_EOF(MAXVUL):
case YY_STATE_EOF(TITLE):
case YY_STATE_EOF(OPENER):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 488 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 488 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 487);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 342 "../src/dealflex.l"

/* epilog section. More C-Code text just written to the ouput file goes here*/

